### ISSUE TITLE
给traefik添加let's encrypt相关配置

### ISSUE THREAD

**Issue by yuchangyuan** [shanghailug/jitsi-deploy#3]
目前有两个域名：
* jitsi.shlug.org
* jitsi-test.shlug.org

**Comment by yuchangyuan** [comment]
还是使用cert-manager?

**Comment by cybernagle** [comment]
dns 是 cloudflare 吗? 如果是 cloudflare 的话, cert 就很方便, lets encrypt 一行代码搞定.

**Comment by yuchangyuan** [comment]
我们应该使用HTTP01 challenge：
1.  最小权限原则，要假定手上没有api token（我也确实没有）；
2. 兼容性，HTTP01不依赖特定的DNS服务提供商；

另外，调试的时候可以用staging环境，避免额度用完

**Comment by cybernagle** [comment]
staging 环境是指, 我们自己的机器嘛 :)

**Comment by yuchangyuan** [comment]
> staging 环境是指, 我们自己的机器嘛 :)

https://letsencrypt.org/docs/staging-environment/

**Comment by yuchangyuan** [comment]
cert-manager的文档：

https://cert-manager.io/docs/installation/helm/
https://cert-manager.io/docs/configuration/acme/http01/#ingresstemplate

**Comment by cybernagle** [comment]
今天稍微看了一下 traefik 的文档. 差不多知道这是个啥了.目前的想法是尽量少引入其他的东西. 找到了下面的文章.  
https://doc.traefik.io/traefik/user-guides/crd-acme/#services 
明天我找时间试一下.

**Comment by cybernagle** [comment]
enterprise 的版本, 才允许多个 pod 的 treafik 的存在, 否则就不支持 Let's Encrypted(应该就是自动签发证书的功能吧). 所以我感觉咱们目前单体就够了. 
refer: By design, Traefik is a stateless application, meaning that it only derives its configuration from the environment it runs in, without additional configuration. For this reason, users can run multiple instances of Traefik at the same time to achieve HA, as is a common pattern in the kubernetes ecosystem 
If you need Let's Encrypt with HA in a Kubernetes environment, we recommend using Traefik Enterprise, which includes distributed Let's Encrypt as a supported feature.

**Comment by yuchangyuan** [comment]
treafik确实是可以的，我们不跑多个实例。不过还要看一下多个域名怎么配置。

**Comment by cybernagle** [comment]
1. k3s without traefik installation. [tutorial](https://rancher.com/docs/k3s/latest/en/networking/#traefik-ingress-controller)
2. deploy traefik with offical helm release. and add configuration like below: 
```
          args:
            - --api.insecure
            - --accesslog
            - --providers.kubernetescrd
            **- --certificatesresolvers.myresolver.acme.tlschallenge**
            **- --certificatesresolvers.myresolver.acme.email=foo@you.com**
            **- --certificatesresolvers.myresolver.acme.storage=acme.json**
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            **- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory**
```
<img width="568" alt="2ea18e6ccd5e5a15663ca443bc2ae2b" src="https://user-images.githubusercontent.com/10879414/164268687-1f487126-dce5-49e5-aeb4-f2e514e94e4e.png">

note: 
we need expose our 80 & 443 port on vm first. otherwise if we create ingressRoute first, it will failed on challenge. (doc: https://doc.traefik.io/traefik/user-guides/crd-acme/#port-forwarding) 

and then ,finally , we can using traefik to expose jitsi web.

**Comment by yuchangyuan** [comment]
1. vm上的端口80和443已经打开
2. 关于acme的email，请使用webmaster@shlug.org（还是使用 shlug@googlegroups.com 这样大家都能看到？）
